export enum MonthsArr {
    NISAN = 'נִיסָן',
    IYYAR = 'אִיָיר',
    SIVAN = 'סִיוָן',
    TAMUZ = 'תַּמּוּז',
    AV = 'אָב',
    ELUL = 'אֱלוּל',
    TISHREI = 'תִשְׁרֵי',
    CHESHVAN = 'חֶשְׁוָן',
    KISLEV = 'כִּסְלֵו',
    TEVET = 'טֵבֵת',
    SHVAT = 'שְׁבָט',
    ADAR_I = 'אַדָר',
    ADAR_II = 'אַדָר ב\'',
}